href: /blog/translation
webSite: Offizielle Website
youtube: YouTube Kanal
facebook: Facebook Page
blog: Blog
interior: Interior Design
projectsPrivate: (Wohnung)
projectsPublic: (Öffentlicher) Raum
designProjects: Projekte (Interior Design)
designStyle: Einrichtungsstil
furniture: Einrichtungsideen
likes: Bewertungen
views: Views
finished: (Realisierte) Projekte
more: Mehr
bathroom: Badezimmer
nursery: Kinderzimmer
kitchen: Küche und Esszimmer
bedroom: Schlafzimmer
livingroom: Wohnzimmer
modern: Modern
modernClassic: Klassische Moderne
classic: Klassik
retro: Retro
contemporary: Contemporary Inneneinrichtung
private: Privat
public: Öffentlich
randomPosts: Das könnte Dich (auch interessiere)
featuredPosts: (Ausgewählte) Beiträge
ideas: Einrichtungsideen
impressions: Bewertungen
from: aus
acherno: 'Acherno'